apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
  namespace: dev-aiagent
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
